INSERT INTO universities (name)
VALUES ('University of Dhaka'),
       ('Bangladesh University of Engineering and Technology'),
       ('University of Chittagong'),
       ('Jahangirnagar University'),
       ('Rajshahi University'),
       ('Khulna University'),
       ('Bangladesh Agricultural University'),
       ('Bangladesh University of Professionals'),
       ('Bangabandhu Sheikh Mujibur Rahman Agricultural University'),
       ('Bangabandhu Sheikh Mujibur Rahman Maritime University'),
       ('Bangabandhu Sheikh Mujibur Rahman Science and Technology University'),
       ('Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University'),
       ('Barisal University'),
       ('Begum Rokeya University'),
       ('Chittagong University of Engineering and Technology'),
       ('Comilla University'),
       ('Dhaka University of Engineering and Technology'),
       ('Dinajpur University'),
       ('Eastern University'),
       ('Hajee Mohammad Danesh Science and Technology University'),
       ('International Islamic University Chittagong'),
       ('Islamic Arabic University'),
       ('Islamic University'),
       ('Jagannath University'),
       ('Jatiya Kabi Kazi Nazrul Islam University'),
       ('Jessore University of Science and Technology'),
       ('Khulna University of Engineering and Technology'),
       ('Mawlana Bhashani Science and Technology University'),
       ('Noakhali Science and Technology University'),
       ('Pabna University of Science and Technology'),
       ('Patuakhali Science and Technology University'),
       ('Premier University, Chittagong'),
       ('Primeasia University'),
       ('Rabindra University'),
       ('Rajshahi University of Engineering and Technology'),
       ('Rangamati Science and Technology University'),
       ('Shahjalal University of Science and Technology'),
       ('Sylhet Agricultural University'),
       ('Sylhet Medical University'),
       ('Sylhet Science and Technology University'),
       ('University of Barisal'),
       ('University of Creative Technology Chittagong'),
       ('University of Development Alternative'),
       ('University of Global Village'),
       ('University of Information Technology and Sciences'),
       ('University of Liberal Arts Bangladesh'),
       ('University of Science and Technology Chittagong'),
       ('University of South Asia'),
       ('University of Asia Pacific'),
       ('University of Science and Technology Meghalaya (Bangladesh Campus)'),
       ('World University of Bangladesh');
